/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlstock;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author hernan
 */
public class CargarProductos extends javax.swing.JFrame
{

    /**
     * Creates new form CargarProductos
     */
    private final ControlStockMain parent;
    private List<Producto> productos; 
    private String ultimoTextField = "";
    private boolean soloStockMin = false;
    private boolean necesitaActualizacion = false; //esto lo uso para cuando se cierra alguna ventana hija
    
    
    public CargarProductos(ControlStockMain referenciaMain)
    {
        parent = referenciaMain;
        
        initComponents();
        setLocationRelativeTo(null);
        
        table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(table.getModel());
        table.setRowSorter(sorter);

        List<RowSorter.SortKey> sortKeys = new ArrayList<>(25);
        sortKeys.add(new RowSorter.SortKey(1, SortOrder.ASCENDING));
        sorter.setSortKeys(sortKeys);

        table.addMouseListener(new MouseAdapter() 
        {
            public void mouseClicked(MouseEvent e) 
            {
                if (e.getClickCount() == 2) 
                {
                   JTable target = (JTable)e.getSource();
                    abrirDetalleProducto(target.getSelectedRow());
                }
            }
        });
        
        setearTabla(ultimoTextField);
    }
    
    private void abrirDetalleProducto(int row)
    {
        if (row < 0)
        {
            return;
        }
        row = table.convertRowIndexToModel(row);
        int cod = Integer.parseInt(table.getModel().getValueAt(row, 0).toString());
        Producto aux = null;
        for (int i = 0; i < productos.size(); i++)
        {
            if (productos.get(i).getCod() == cod)
            {
                aux = productos.get(i);
                break;
            }
        }
        
        if (aux == null)
        {
            return;
        }
        
        this.setFocusable(false);
        this.setEnabled(false);
        necesitaActualizacion = true;
        new DetalleProducto(this, aux, true, parent.getDB()).setVisible(true);
    }
    
    private void setearTabla(String indiceBusqueda)
    {
        table.removeAll();

        try
        {
            productos = parent.getDB().getMultipleByNombre(indiceBusqueda);
        } catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(this, "Internal SQL error", "Error", JOptionPane.ERROR_MESSAGE);
            Volver();
        }
        
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        while (model.getRowCount() != 0)
        {
            model.removeRow(0);
        }
        
        Producto aux;
        for (int i = 0; i < productos.size(); i++)
        {
            aux = productos.get(i);
            if (indiceBusqueda.equals("") || aux.getNombre().contains(indiceBusqueda))
            {
                if (!soloStockMin || aux.estaEnStockMinimo())
                {
                    model.addRow(new Object[]{aux.getCod(), aux.getNombre(), aux.getDescripcion(), aux.getStock(), aux.getValorStockMin()});
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        volverButton = new javax.swing.JButton();
        buscarTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        stockMinimoCheckBox = new javax.swing.JCheckBox();
        agregarProductoButton = new javax.swing.JButton();
        filtrarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Modificar Productos");
        addWindowStateListener(new java.awt.event.WindowStateListener()
        {
            public void windowStateChanged(java.awt.event.WindowEvent evt)
            {
                formWindowStateChanged(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener()
        {
            public void windowGainedFocus(java.awt.event.WindowEvent evt)
            {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt)
            {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Código", "Nombre", "Descripción", "Stock actual", "Stock mínimo"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0)
        {
            table.getColumnModel().getColumn(0).setPreferredWidth(20);
            table.getColumnModel().getColumn(3).setPreferredWidth(25);
            table.getColumnModel().getColumn(4).setPreferredWidth(25);
        }

        volverButton.setText("Volver");
        volverButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                volverButtonActionPerformed(evt);
            }
        });

        buscarTextField.addInputMethodListener(new java.awt.event.InputMethodListener()
        {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt)
            {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt)
            {
                buscarTextFieldInputMethodTextChanged(evt);
            }
        });
        buscarTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buscarTextFieldActionPerformed(evt);
            }
        });
        buscarTextField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                buscarTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                buscarTextFieldKeyReleased(evt);
            }
        });

        jLabel1.setText("Buscar:");

        stockMinimoCheckBox.setText("Ver solo productos con stock mínimo");
        stockMinimoCheckBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                stockMinimoCheckBoxActionPerformed(evt);
            }
        });

        agregarProductoButton.setBackground(new java.awt.Color(0, 153, 0));
        agregarProductoButton.setText("Agregar producto nuevo");
        agregarProductoButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                agregarProductoButtonActionPerformed(evt);
            }
        });

        filtrarButton.setText("FIltrar");
        filtrarButton.setName(""); // NOI18N
        filtrarButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                filtrarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(stockMinimoCheckBox))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filtrarButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(agregarProductoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(volverButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buscarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(filtrarButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stockMinimoCheckBox)
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(agregarProductoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volverButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_volverButtonActionPerformed
    {//GEN-HEADEREND:event_volverButtonActionPerformed
        // TODO add your handling code here:
        Volver();
    }//GEN-LAST:event_volverButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        // TODO add your handling code here:
        Volver();
    }//GEN-LAST:event_formWindowClosing

    private void buscarTextFieldInputMethodTextChanged(java.awt.event.InputMethodEvent evt)//GEN-FIRST:event_buscarTextFieldInputMethodTextChanged
    {//GEN-HEADEREND:event_buscarTextFieldInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_buscarTextFieldInputMethodTextChanged

    private void buscarTextFieldKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_buscarTextFieldKeyPressed
    {//GEN-HEADEREND:event_buscarTextFieldKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_buscarTextFieldKeyPressed

    private void buscarTextFieldKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_buscarTextFieldKeyReleased
    {//GEN-HEADEREND:event_buscarTextFieldKeyReleased
        // TODO add your handling code here:
        /*if (buscarTextField.getText().equals(ultimoTextField))
        {
            return;
        }*/
        //buscarTextField.setText(buscarTextField.getText().toUpperCase());
        ultimoTextField = buscarTextField.getText();
        //setearTabla(ultimoTextField);
        //System.out.println("cambiooo");
    }//GEN-LAST:event_buscarTextFieldKeyReleased

    private void stockMinimoCheckBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_stockMinimoCheckBoxActionPerformed
    {//GEN-HEADEREND:event_stockMinimoCheckBoxActionPerformed
        // TODO add your handling code here:
        if (soloStockMin)
        {
            soloStockMin = false;
        }
        else
        {
            soloStockMin = true;
        }
        setearTabla(buscarTextField.getText());
    }//GEN-LAST:event_stockMinimoCheckBoxActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowStateChanged
    {//GEN-HEADEREND:event_formWindowStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowStateChanged

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowGainedFocus
    {//GEN-HEADEREND:event_formWindowGainedFocus
        // TODO add your handling code here:
        if (necesitaActualizacion)
        {
            necesitaActualizacion = false;
            setearTabla(ultimoTextField);
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void agregarProductoButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_agregarProductoButtonActionPerformed
    {//GEN-HEADEREND:event_agregarProductoButtonActionPerformed
        // TODO add your handling code here:
        this.setFocusable(false);
        this.setEnabled(false);
        necesitaActualizacion = true;
        new NuevoProducto(this, parent.getDB()).setVisible(true);
    }//GEN-LAST:event_agregarProductoButtonActionPerformed

    private void buscarTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buscarTextFieldActionPerformed
    {//GEN-HEADEREND:event_buscarTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarTextFieldActionPerformed

    private void filtrarButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_filtrarButtonActionPerformed
    {//GEN-HEADEREND:event_filtrarButtonActionPerformed
        // TODO add your handling code here:
        setearTabla(ultimoTextField);

    }//GEN-LAST:event_filtrarButtonActionPerformed

    private void Volver()
    {
        this.setEnabled(false);
        this.setVisible(false);
        parent.setEnabled(true);
        parent.setFocusable(true);
        parent.setVisible(true);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarProductoButton;
    private javax.swing.JTextField buscarTextField;
    private javax.swing.JButton filtrarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox stockMinimoCheckBox;
    private javax.swing.JTable table;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables
}
