/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlstock;

import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author hernan
 */
public final class ControlStockMain extends javax.swing.JFrame
{
    private static final String BD_NAME = "stock-control-db.db";
    private Database db;
    private ResourceBundle rb;
    /**
     * Creates new form ControlStock
     */
    
    

    public ControlStockMain()
    {
        initComponents();
        setLocationRelativeTo(null);
        
        
        SetLanguage();
        InitDatabase();
        
        //CargarTestData();
    }

    private void InitDatabase()
    {
        db = new Database();
        if (!db.init(BD_NAME))
        {
            JOptionPane.showMessageDialog(this, rb.getString("DbNotFound"), rb.getString("Error"), JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
    }
    
    private void SetLanguage()
    {
        rb = LangConfig.getInstance().getResourceBundle();
        
        this.setTitle(rb.getString("Title"));
        tituloLabel.setText(rb.getString("Title"));
        controlLabel.setText(rb.getString("Control"));
        cargaLabel.setText(rb.getString("Load"));
        verProductosButton.setText(rb.getString("ViewProducts"));
        generarReporteButton.setText(rb.getString("GenerateReport"));
        modificarProductosButton.setText(rb.getString("EditProducts"));
        modificarStockButton.setText(rb.getString("ChangeStock"));
        salirButton.setText(rb.getString("Exit"));
        salirMenuItem.setText(rb.getString("Exit"));
        archivoMenu.setText(rb.getString("File"));
        ayudaMenu.setText(rb.getString("Help"));
        acercaDeMenuItem.setText(rb.getString("About"));
        langMenu.setText(rb.getString("Language"));
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        tituloLabel = new javax.swing.JLabel();
        salirButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        verProductosButton = new javax.swing.JButton();
        generarReporteButton = new javax.swing.JButton();
        cargaLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        modificarProductosButton = new javax.swing.JButton();
        modificarStockButton = new javax.swing.JButton();
        controlLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        archivoMenu = new javax.swing.JMenu();
        salirMenuItem = new javax.swing.JMenuItem();
        ayudaMenu = new javax.swing.JMenu();
        acercaDeMenuItem = new javax.swing.JMenuItem();
        langMenu = new javax.swing.JMenu();
        englishMenuItem = new javax.swing.JMenuItem();
        españolMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Control De Stock");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        tituloLabel.setFont(new java.awt.Font("BankGothic Lt BT", 0, 36)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(255, 102, 0));
        tituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLabel.setText("Control De Stock");

        salirButton.setBackground(new java.awt.Color(255, 51, 51));
        salirButton.setText("Salir");
        salirButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                salirButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        verProductosButton.setText("Listar productos");
        verProductosButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                verProductosButtonActionPerformed(evt);
            }
        });

        generarReporteButton.setText("Generar reporte");
        generarReporteButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                generarReporteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verProductosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(generarReporteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(verProductosButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(generarReporteButton))
        );

        cargaLabel.setFont(new java.awt.Font("BankGothic Lt BT", 0, 18)); // NOI18N
        cargaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cargaLabel.setText("Carga");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        modificarProductosButton.setText("Modificar productos");
        modificarProductosButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                modificarProductosButtonActionPerformed(evt);
            }
        });

        modificarStockButton.setText("Cargar stock");
        modificarStockButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                modificarStockButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modificarProductosButton, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(modificarStockButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(modificarProductosButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modificarStockButton))
        );

        controlLabel.setFont(new java.awt.Font("BankGothic Lt BT", 0, 18)); // NOI18N
        controlLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        controlLabel.setText("Control");

        archivoMenu.setText("Archivo");

        salirMenuItem.setText("Salir");
        salirMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                salirMenuItemActionPerformed(evt);
            }
        });
        archivoMenu.add(salirMenuItem);

        jMenuBar1.add(archivoMenu);

        ayudaMenu.setText("Ayuda");

        acercaDeMenuItem.setText("Acerca de");
        acercaDeMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                acercaDeMenuItemActionPerformed(evt);
            }
        });
        ayudaMenu.add(acercaDeMenuItem);

        jMenuBar1.add(ayudaMenu);

        langMenu.setText("Lenguaje");

        englishMenuItem.setText("English");
        englishMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                englishMenuItemActionPerformed(evt);
            }
        });
        langMenu.add(englishMenuItem);

        españolMenuItem.setText("Español");
        españolMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                españolMenuItemActionPerformed(evt);
            }
        });
        langMenu.add(españolMenuItem);

        jMenuBar1.add(langMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(controlLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cargaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(controlLabel)
                    .addComponent(cargaLabel))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 24, Short.MAX_VALUE)
                .addComponent(salirButton)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generarReporteButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_generarReporteButtonActionPerformed
    {//GEN-HEADEREND:event_generarReporteButtonActionPerformed
        // TODO add your handling code here:
        this.setFocusable(false);
        this.setEnabled(false);
        new GenerarReporte(this).setVisible(true);
    }//GEN-LAST:event_generarReporteButtonActionPerformed

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_salirButtonActionPerformed
    {//GEN-HEADEREND:event_salirButtonActionPerformed
        // TODO add your handling code here:
        Salir();
    }//GEN-LAST:event_salirButtonActionPerformed

    private void verProductosButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_verProductosButtonActionPerformed
    {//GEN-HEADEREND:event_verProductosButtonActionPerformed
        // TODO add your handling code here:
        this.setFocusable(false);
        this.setEnabled(false);
        new VerProductos(this).setVisible(true);
    }//GEN-LAST:event_verProductosButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        // TODO add your handling code here:
        Salir();
    }//GEN-LAST:event_formWindowClosing

    private void salirMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_salirMenuItemActionPerformed
    {//GEN-HEADEREND:event_salirMenuItemActionPerformed
        // TODO add your handling code here:
        Salir();
    }//GEN-LAST:event_salirMenuItemActionPerformed

    private void modificarStockButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_modificarStockButtonActionPerformed
    {//GEN-HEADEREND:event_modificarStockButtonActionPerformed
        // TODO add your handling code here:
        this.setFocusable(false);
        this.setEnabled(false);
        new CargarStock(this).setVisible(true);
    }//GEN-LAST:event_modificarStockButtonActionPerformed

    private void modificarProductosButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_modificarProductosButtonActionPerformed
    {//GEN-HEADEREND:event_modificarProductosButtonActionPerformed
        // TODO add your handling code here:
        this.setFocusable(false);
        this.setEnabled(false);
        new CargarProductos(this).setVisible(true);
    }//GEN-LAST:event_modificarProductosButtonActionPerformed

    private void acercaDeMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_acercaDeMenuItemActionPerformed
    {//GEN-HEADEREND:event_acercaDeMenuItemActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, rb.getString("AboutDesc"), rb.getString("About"), JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_acercaDeMenuItemActionPerformed

    private void englishMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_englishMenuItemActionPerformed
    {//GEN-HEADEREND:event_englishMenuItemActionPerformed
        // TODO add your handling code here:
        LangConfig.getInstance().SetLanguage("en");
        SetLanguage();
        
    }//GEN-LAST:event_englishMenuItemActionPerformed

    private void españolMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_españolMenuItemActionPerformed
    {//GEN-HEADEREND:event_españolMenuItemActionPerformed
        // TODO add your handling code here:
        LangConfig.getInstance().SetLanguage("es");
        SetLanguage();
    }//GEN-LAST:event_españolMenuItemActionPerformed
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ControlStockMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ControlStockMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ControlStockMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ControlStockMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ControlStockMain().setVisible(true);
            }
        });
    }
    
    private void Salir()
    {
        int showConfirmDialog = JOptionPane.showConfirmDialog(this, rb.getString("ExitConfirm"), rb.getString("Exit"), JOptionPane.OK_CANCEL_OPTION);
        if (showConfirmDialog == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }
    
    public Database getDB()
    {
        return db;
    }
    
    /*
    private void CargarTestData()
    {
        
        Producto aux;
        List<Producto> productos = new ArrayList<Producto>();
        
        for (int i = 0; i < 20; i++)
        {
            aux = new Producto();
            aux.setData("PRODUCTO " + i, "DESCRIPCION " + i , 0, 5);
            aux.setStock(i);
            productos.add(aux);
        }
        
        for (int i = 0; i < 20; i++)
        {
            aux = new Producto();
            aux.setData("CAJA " + i, "DESCRIPCION CAJA " + i , 0, 5);
            aux.setStock(i);
            productos.add(aux);
        }
        
        for (int i = 0; i < 12; i++)
        {
            aux = new Producto();
            aux.setData("CAJON " + i, "DESCRIPCION CAJON " + i , 0, 5);
            aux.setStock(i);
            productos.add(aux);
        }
        
        for (int i = 0; i < 15; i++)
        {
            aux = new Producto();
            aux.setData("MADERA " + i, "DESCRIPCION MADERA " + i , 0, 5);
            aux.setStock(i);
            productos.add(aux);
        }
        
        for (int i = 0; i < productos.size(); i++)
        {
            try
            {
                db.AgregarProducto(productos.get(i));
            } catch (SQLException ex)
            {
                Logger.getLogger(ControlStockMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem acercaDeMenuItem;
    private javax.swing.JMenu archivoMenu;
    private javax.swing.JMenu ayudaMenu;
    private javax.swing.JLabel cargaLabel;
    private javax.swing.JLabel controlLabel;
    private javax.swing.JMenuItem englishMenuItem;
    private javax.swing.JMenuItem españolMenuItem;
    private javax.swing.JButton generarReporteButton;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu langMenu;
    private javax.swing.JButton modificarProductosButton;
    private javax.swing.JButton modificarStockButton;
    private javax.swing.JButton salirButton;
    private javax.swing.JMenuItem salirMenuItem;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JButton verProductosButton;
    // End of variables declaration//GEN-END:variables
}
