/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlstock;

import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.ResourceBundle;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author hernan
 */


public class DetalleProducto extends javax.swing.JFrame
{
    private final JFrame parent;
    private final Producto producto;
    private final boolean modificable;
    private final Database db;
    private ResourceBundle rb;

    public DetalleProducto() throws HeadlessException
    {
        this.parent = null;
        this.producto = null;
        this.modificable = false;
        this.db = null;
    }
    
    public DetalleProducto(JFrame parent, Producto producto,boolean modificable, Database db)
    {
        initComponents();
        setLocationRelativeTo(null);
        
        SetLanguage();
        
        this.parent = parent;
        this.producto = producto;
        this.modificable = modificable;
        this.db = db;
        
        volverButton.requestFocus();
        
        nombreTextField.setText(producto.getNombre());
        descripcionTextField.setText(producto.getDescripcion());
        stockMinimoTextField.setText(String.valueOf(producto.getValorStockMin()));
        stockActualTextField.setText(String.valueOf(producto.getStock()));
        codigoTextField.setText(String.valueOf(producto.getCod()));
        
        if (!modificable)
        {
            guardarCambiosButton.setVisible(false);
            eliminarButton.setVisible(false);

            nombreTextField.setEditable(false);
            descripcionTextField.setEditable(false);
            stockActualTextField.setEditable(false);
            stockMinimoTextField.setEditable(false);
            
            nombreTextField.setFocusable(false);
            descripcionTextField.setFocusable(false);
            stockActualTextField.setFocusable(false);
            stockMinimoTextField.setFocusable(false);
        }
    }
    
    private void SetLanguage()
    {
        rb = LangConfig.getInstance().getResourceBundle();
        
        this.setTitle(rb.getString("ProductDetails"));
        
        volverButton.setText(rb.getString("Back"));
        guardarCambiosButton.setText(rb.getString("SaveChanges"));
        eliminarButton.setText(rb.getString("Delete"));
        codigoLabel.setText(rb.getString("Code"));
        nombreLabel.setText(rb.getString("Name"));
        descriptionLabel.setText(rb.getString("Description"));
        currentStockLabel.setText(rb.getString("CurrentStock"));
        minStockLabel.setText(rb.getString("MinStock"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        nombreLabel = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        descriptionLabel = new javax.swing.JLabel();
        descripcionTextField = new javax.swing.JTextField();
        currentStockLabel = new javax.swing.JLabel();
        stockActualTextField = new javax.swing.JTextField();
        minStockLabel = new javax.swing.JLabel();
        stockMinimoTextField = new javax.swing.JTextField();
        volverButton = new javax.swing.JButton();
        guardarCambiosButton = new javax.swing.JButton();
        codigoLabel = new javax.swing.JLabel();
        codigoTextField = new javax.swing.JTextField();
        eliminarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Detalle De Producto");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        nombreLabel.setText("Nombre:");

        nombreTextField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                nombreTextFieldKeyReleased(evt);
            }
        });

        descriptionLabel.setText("Descripción:");

        descripcionTextField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                descripcionTextFieldKeyReleased(evt);
            }
        });

        currentStockLabel.setText("Stock actual:");

        stockActualTextField.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                stockActualTextFieldFocusLost(evt);
            }
        });
        stockActualTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                stockActualTextFieldActionPerformed(evt);
            }
        });
        stockActualTextField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                stockActualTextFieldKeyReleased(evt);
            }
        });

        minStockLabel.setText("Stock mínimo:");

        stockMinimoTextField.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                stockMinimoTextFieldFocusLost(evt);
            }
        });
        stockMinimoTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                stockMinimoTextFieldActionPerformed(evt);
            }
        });
        stockMinimoTextField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                stockMinimoTextFieldKeyReleased(evt);
            }
        });

        volverButton.setText("Volver");
        volverButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                volverButtonActionPerformed(evt);
            }
        });

        guardarCambiosButton.setBackground(new java.awt.Color(0, 153, 0));
        guardarCambiosButton.setText("Guardar cambios");
        guardarCambiosButton.setEnabled(false);
        guardarCambiosButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                guardarCambiosButtonActionPerformed(evt);
            }
        });

        codigoLabel.setText("Código:");

        codigoTextField.setEnabled(false);
        codigoTextField.setFocusable(false);
        codigoTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                codigoTextFieldActionPerformed(evt);
            }
        });

        eliminarButton.setBackground(new java.awt.Color(255, 0, 0));
        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                eliminarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guardarCambiosButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volverButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(descriptionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(descripcionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombreLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(currentStockLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stockActualTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(minStockLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stockMinimoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(codigoLabel)
                        .addGap(32, 32, 32)
                        .addComponent(codigoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eliminarButton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(16, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codigoLabel)
                            .addComponent(codigoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(eliminarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descriptionLabel)
                    .addComponent(descripcionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentStockLabel)
                    .addComponent(stockActualTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stockMinimoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minStockLabel))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(volverButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guardarCambiosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stockActualTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_stockActualTextFieldActionPerformed
    {//GEN-HEADEREND:event_stockActualTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockActualTextFieldActionPerformed

    private void stockMinimoTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_stockMinimoTextFieldActionPerformed
    {//GEN-HEADEREND:event_stockMinimoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockMinimoTextFieldActionPerformed

    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_volverButtonActionPerformed
    {//GEN-HEADEREND:event_volverButtonActionPerformed
        // TODO add your handling code here:
        Volver();
    }//GEN-LAST:event_volverButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        // TODO add your handling code here:
        Volver();
    }//GEN-LAST:event_formWindowClosing

    private void guardarCambiosButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_guardarCambiosButtonActionPerformed
    {//GEN-HEADEREND:event_guardarCambiosButtonActionPerformed
        if (!ValidarData())
        {
            JOptionPane.showMessageDialog(this, rb.getString("ValidationError"), rb.getString("Error"), JOptionPane.ERROR_MESSAGE);
            return;
        }
        producto.setData(nombreTextField.getText(), descripcionTextField.getText(), producto.getStock(), Integer.parseInt(stockMinimoTextField.getText()));
        producto.setStock(Integer.parseInt(stockActualTextField.getText()));

        try
        {
            db.ModificarProducto(producto);
        } catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(this, "SQL error", rb.getString("Error"), JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Volver();
    }//GEN-LAST:event_guardarCambiosButtonActionPerformed

    private boolean ValidarData()
    {
        if (stockActualTextField.getText().equals(""))
        {
            stockActualTextField.setText("0");
        }
        else
        {
            try 
            {
                int a = Integer.parseInt(stockActualTextField.getText());
                if (a < 0)
                {
                    throw new NumberFormatException();
                }
            }
            catch (NumberFormatException e) 
            {
                 JOptionPane.showMessageDialog(this, rb.getString("StockValidationError"), rb.getString("Error"), JOptionPane.ERROR_MESSAGE);
                 return false;
            }
        }
        
        if (stockMinimoTextField.getText().equals(""))
        {
            stockMinimoTextField.setText("0");
        }
        else
        {
            try 
            {
                int a = Integer.parseInt(stockMinimoTextField.getText());
                
                if (a < 0)
                {
                    throw new NumberFormatException();
                }
            }
            catch (NumberFormatException e) 
            {
                 JOptionPane.showMessageDialog(this, rb.getString("MinStockValidationError"), rb.getString("Error"), JOptionPane.ERROR_MESSAGE);
                 return false;
            }
        }
        
        /*nombreTextField.setText(nombreTextField.getText().toUpperCase());
        descripcionTextField.setText(descripcionTextField.getText().toUpperCase());*/
        
        if (nombreTextField.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, rb.getString("NameValidationError"), rb.getString("Error"), JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if (!nombreTextField.getText().equals(producto.getNombre()))
        {
            try
            {
                //Si al producto se le cambio el nombre, compruebo que no exista otro producto con el mismo nombre
                if (db.productoExisteByNombre(producto.getNombre()))
                {
                    JOptionPane.showMessageDialog(this, rb.getString("DuplicateNameError"), rb.getString("Error"), JOptionPane.ERROR_MESSAGE);
                    return false;
                }
            } catch (SQLException ex)
            {
                return false;
            }
        }
        return true;
    }
    
    private void codigoTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_codigoTextFieldActionPerformed
    {//GEN-HEADEREND:event_codigoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoTextFieldActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_eliminarButtonActionPerformed
    {//GEN-HEADEREND:event_eliminarButtonActionPerformed
        // TODO add your handling code here:
        int showConfirmDialog = JOptionPane.showConfirmDialog(this, rb.getString("DeleteConfirmation"), rb.getString("Delete"), JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
        if (showConfirmDialog == JOptionPane.YES_OPTION)
        {
            try
            {
                db.EliminarProducto(producto.getCod());
            } 
            catch (SQLException ex)
            {
                JOptionPane.showMessageDialog(this, "SQL error", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Volver();
        }
    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void stockActualTextFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_stockActualTextFieldFocusLost
    {//GEN-HEADEREND:event_stockActualTextFieldFocusLost
        // TODO add your handling code here:
        if (stockActualTextField.getText().equals(""))
        {
            stockActualTextField.setText("0");
        }
        
    }//GEN-LAST:event_stockActualTextFieldFocusLost

    private void stockMinimoTextFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_stockMinimoTextFieldFocusLost
    {//GEN-HEADEREND:event_stockMinimoTextFieldFocusLost
        // TODO add your handling code here:
        if (stockMinimoTextField.getText().equals(""))
        {
            stockMinimoTextField.setText("0");
        }
    }//GEN-LAST:event_stockMinimoTextFieldFocusLost

    private void nombreTextFieldKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nombreTextFieldKeyReleased
    {//GEN-HEADEREND:event_nombreTextFieldKeyReleased
        // TODO add your handling code here:
        //nombreTextField.setText(nombreTextField.getText().toUpperCase());
        ActivarGuardarCambiosButton();
        
    }//GEN-LAST:event_nombreTextFieldKeyReleased

    private void descripcionTextFieldKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_descripcionTextFieldKeyReleased
    {//GEN-HEADEREND:event_descripcionTextFieldKeyReleased
        // TODO add your handling code here:
        //descripcionTextField.setText(descripcionTextField.getText().toUpperCase());
        ActivarGuardarCambiosButton();
    }//GEN-LAST:event_descripcionTextFieldKeyReleased

    private void stockActualTextFieldKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_stockActualTextFieldKeyReleased
    {//GEN-HEADEREND:event_stockActualTextFieldKeyReleased
        // TODO add your handling code here:
        ActivarGuardarCambiosButton();
    }//GEN-LAST:event_stockActualTextFieldKeyReleased

    private void stockMinimoTextFieldKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_stockMinimoTextFieldKeyReleased
    {//GEN-HEADEREND:event_stockMinimoTextFieldKeyReleased
        // TODO add your handling code here:
        ActivarGuardarCambiosButton();
    }//GEN-LAST:event_stockMinimoTextFieldKeyReleased

    private void ActivarGuardarCambiosButton()
    {
        if (!guardarCambiosButton.isEnabled() && modificable)
        {
            guardarCambiosButton.setEnabled(true);
        }
    }
    
    private void Volver()
    {
        parent.setEnabled(true);
        parent.setFocusable(true);
        parent.setVisible(true);
        this.dispose();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JTextField codigoTextField;
    private javax.swing.JLabel currentStockLabel;
    private javax.swing.JTextField descripcionTextField;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JButton guardarCambiosButton;
    private javax.swing.JLabel minStockLabel;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JTextField stockActualTextField;
    private javax.swing.JTextField stockMinimoTextField;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables
}
